version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rental_agent
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rental_user:rental_pass@postgres:5432/rental_agent
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data: